apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-openweather-deployment
  labels:
    app: docker-k8s-openweather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-openweather
  template:
    metadata:
      labels:
        app: docker-k8s-openweather
    spec:
      containers:
        - name: docker-k8s-openweather
          image: mfrac/openweatherapp
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001